source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'
use_frameworks! :linkage => :static

target 'ObjCDemo' do
  # Integrates the PayKit SDK from GitHub. PayKit.podspec declares:
  # - WechatOpenSDK-XCFramework
  # - AlipaySDK-iOS
  pod 'PayKit', :git => 'https://github.com/mhqamx/PayKit.git', :tag => '0.2.0'
end
